;;;; pe-001-to-099.lisp ---
;;;; Created  : <2020-02-09 Sun 22:13:59 GMT>
;;;; Modified : <2020-02-11 Tue 23:50:30 GMT>

(in-package :peh)


(defun pe-001 ()
  "Title: MULTIPLES OF 3 AND 5
Credits: https://projecteuler.net/problem=1

If we list all the natural numbers below 10 that are multiples of 3 or
5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000."
  (loop :for n :from 1 :to 1000
     :when (or (zerop (mod n 3))
               (zerop (mod n 5)))
     :sum n))


(defun pe-002 ()
  "Title: EVEN FIBONACCI NUMBERS
Credits: https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the
 previous two terms.  By starting with 1 and 2, the first 10 terms
 will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... , F(n-1) + F(n+1)

By considering the terms in the Fibonacci sequence whose values do not
 exceed fou million, find the sum of the even-valued terms."
  (loop :for i :from (peh/utils:fib 1) do
       (print (peh/utils:fib i))
     :until (< 4000000 (peh/utils:fib i))))

;;;; pe-001-to-099.lisp
